iFramework.Web.Admin/Areas/OA/Controllers/OrgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using iFramework.OA.Contract;
using iFramework.Account.Contract;
using iFramework.Web.Admin.Common;
using iFramework.Framework.Utility;

namespace iFramework.Web.Admin.Areas.OA.Controllers
{
    [Permission(EnumBusinessPermission.OAManage_Org)]
    public class OrgController : AdminControllerBase
    {
        //
        // GET: /OA/Org/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetOrg()
        {
            var rootBranch = this.OAService.GetOrg();

            return Json(rootBranch, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveOrg()
        {
            try
            {
                int bytelength = Request.ContentLength;
                byte[] inputbytes = Request.BinaryRead(bytelength);
                string message = System.Text.Encoding.UTF8.GetString(inputbytes);
                var branch = JsonConvert.DeserializeObject<Branch>(message);

                this.OAService.SaveOrg(branch);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }

            return Content("保存成功！");
        }
    }
}

iFramework.Web.Admin/Areas/OA/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iFramework.OA.Contract;
using iFramework.Account.Contract;
using iFramework.Web.Admin.Common;
using iFramework.Framework.Utility;

namespace iFramework.Web.Admin.Areas.OA.Controllers
{
    [Permission(EnumBusinessPermission.OAManage_Staff)]
    public class StaffController : AdminControllerBase
    {
        //
        // GET: /OA/Staff/

        public ActionResult Index(StaffRequest request)
        {
            var result = this.OAService.GetStaffList(request);
            return View(result);
        }

        //
        // GET: /OA/Staff/Create

        public ActionResult Create()
        {
            var model = new Staff() { };
            this.RenderMyViewData(model);
            return View("Edit", model);
        }

        //
        // POST: /OA/Staff/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var model = new Staff();
            this.TryUpdateModel<Staff>(model);

            this.OAService.SaveStaff(model);

            return this.RefreshParent();
        }

        //
        // GET: /OA/Staff/Edit/5

        public ActionResult Edit(int id)
        {
            var model = this.OAService.GetStaff(id);
            this.RenderMyViewData(model);
            return View(model);
        }

        //
        // POST: /OA/Staff/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var model = this.OAService.GetStaff(id);
            this.TryUpdateModel<Staff>(model);

            this.OAService.SaveStaff(model);

            return this.RefreshParent();
        }

        // POST: /OA/Staff/Delete/5

        [HttpPost]
        public ActionResult Delete(List<int> ids)
        {
            this.OAService.DeleteStaff(ids);
            return RedirectToAction("Index");
        }

        private void RenderMyViewData(Staff model)
        {
            ViewData.Add("Position", new SelectList(EnumHelper.GetItemValueList<EnumPosition>(), "Key", "Value", model.Position));
            ViewData.Add("Gender", new SelectList(EnumHelper.GetItemValueList<EnumGender>(), "Key", "Value", model.Gender));
        }
    }
}

iFramework.Web.Admin/Areas/OA/Views/Staff/Edit.cshtml
@using iFramework.Framework.Contract
@using iFramework.Framework.Web.Controls
@using iFramework.Framework.Utility
@using iFramework.OA.Contract
@using iFramework.Web
@model Staff
@{
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}
@section PageSpecificStyleSheetIncludes{
    <style type="text/css">
        .controls label
        {
            display:inline;
        }
    </style>
}
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript">
        $("#BirthDate").datepicker();
   </script>
}
@section MainContent{
<div class="portlet-body form-horizontal form-bordered form-row-stripped">
    <div class="row-fluid"> 
            <div class="alert alert-info">
                <button class="close" data-dismiss="alert"></button>
                分配到部门请到<strong>“组织结构管理”</strong>菜单操作！
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>姓名：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Name, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Name)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">职位：</label>
                <div class="controls">
                @Html.DropDownList("Position", "暂无")   
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Position)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">性别：</label>
                <div class="controls">
                @Html.RadioBoxList("Gender")   
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Gender)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">生日：</label>
                <div class="controls">
                @Html.TextBox("BirthDate", Model.BirthDate.ToCnDataString(),  new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.BirthDate)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">电子邮件：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Email, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Email)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">电话：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Tel, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Tel)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">联系地址：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Address, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Address)</span>
                </div>
            </div>
            
    </div>
</div>
}


iFramework.Web.Admin/Areas/OA/Views/Staff/Index.cshtml
@using iFramework.Framework.Contract
@using iFramework.Framework.Utility
@using iFramework.Framework.Web.Controls
@using iFramework.OA.Contract

@model PagedList<Staff>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" id="delete" href="javascript:;"><i class="icon-trash icon-white"></i> 删除</a>
            <a class="btn blue thickbox" title='添加新员工' href="@Url.Action("Create")?TB_iframe=true&height=400&width=500"><i class="icon-plus icon-white"></i> 新增</a>
        </div>
    </div>
    <div class="span8">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search" }))
        { 
        <div class="dataTables_filter">
            <label>
                <button type="submit" class="btn">搜索 <i class="icon-search"></i></button>
             </label>
            <label>
                <span>姓名：</span>
                @Html.TextBox("Name", null, new { @class = "m-wrap small" })
            </label>
        </div>
        }
    </div>
</div>

<div class="alert alert-info">
    <button class="close" data-dismiss="alert"></button>
    分配到相关部门请到 <strong>“<a href="@Url.Action("Index", "Org")">组织结构管理</a>”</strong>菜单操作！
</div>

@using (Html.BeginForm("Delete", "Staff", FormMethod.Post, new { id = "mainForm" }))
{
<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th style="width: 8px;">
                <input type="checkbox" id="checkall" class="group-checkable" />
            </th>
            <th>
                姓名
            </th>
            <th>
                职位
            </th>
            <th>
                部门
            </th>
            <th>
                性别
            </th>
            <th>
                生日
            </th>
            <th>
                电子邮件
            </th>
            <th>
                电话
            </th>
            <th>
                联系地址
            </th>
            <th>
                操作
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
        <tr>
            <td>
                <input type="checkbox" class="checkboxes" name='ids' value='@m.ID' />
            </td>
            <td>
                @m.Name
            </td>
            <td>
                @EnumHelper.GetEnumTitle((EnumPosition)m.Position)
            </td>
            <td>
                @(m.Branch == null ? "未分配" : m.Branch.Name)
            </td>
            <td>
                @EnumHelper.GetEnumTitle((EnumGender)m.Gender)
            </td>
            <td>
                @m.BirthDate.ToCnDataString()
            </td>
            <td>
                @m.Email
            </td>
            <td>
                @m.Tel
            </td>
            <td>
                @m.Address
            </td>
            <td>
                <a class="btn mini purple thickbox" title='编辑员工信息' href="@Url.Action("Edit", new { id = m.ID })?TB_iframe=true&height=400&width=500">
                    <i class="icon-edit"></i>
                    编辑
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>
