iFramework.Web.Admin/Areas/Crm/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using iFramework.Crm.Contract;
using iFramework.Account.Contract;
using iFramework.Web.Admin.Common;

using iFramework.Framework.Utility;

namespace iFramework.Web.Admin.Areas.Crm.Controllers
{
    [Permission(EnumBusinessPermission.CrmManage_Project)]
    public class ProjectController : AdminControllerBase
    {
        //
        // GET: /Crm/Project/

        public ActionResult Index(ProjectRequest request)
        {
            var result = this.CrmService.GetProjectList(request);
            return View(result);
        }

        //
        // GET: /Crm/Project/Create

        public ActionResult Create()
        {
            var model = new Project() {  };
            return View("Edit", model);
        }

        //
        // POST: /Crm/Project/Create

        [System.Web.Mvc.HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var model = new Project();
            this.TryUpdateModel<Project>(model);

            this.CrmService.SaveProject(model);

            return this.RefreshParent();
        }

        //
        // GET: /Crm/Project/Edit/5

        public ActionResult Edit(int id)
        {
            var model = this.CrmService.GetProject(id);
            return View(model);
        }

        //
        // POST: /Crm/Project/Edit/5

        [System.Web.Mvc.HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var model = this.CrmService.GetProject(id);
            this.TryUpdateModel<Project>(model);

            this.CrmService.SaveProject(model);

            return this.RefreshParent();
        }

        // POST: /Crm/Project/Delete/5

        [System.Web.Mvc.HttpPost]
        public ActionResult Delete(List<int> ids)
        {
            this.CrmService.DeleteProject(ids);
            return RedirectToAction("Index");
        }
    }
}

iFramework.Web.Admin/Areas/Crm/Views/Project/Edit.cshtml
@using iFramework.Framework.Contract
@using iFramework.Framework.Web.Controls
@using iFramework.Crm.Contract
@using iFramework.Web
@model Project
@{
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}
@section PageSpecificStyleSheetIncludes{
}
@section PageSpecificJavascriptIncludes{
}
@section MainContent{
<div class="portlet-body form-horizontal form-bordered form-row-stripped">
    <div class="row-fluid"> 
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>名称：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Name, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Name)</span>
                </div>
            </div>

    </div>
</div>
}

iFramework.Web.Admin/Areas/Crm/Views/Project/Index.cshtml
@using iFramework.Framework.Contract
@using iFramework.Framework.Utility
@using iFramework.Framework.Web.Controls
@using iFramework.Crm.Contract

@model PagedList<Project>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" id="delete" href="javascript:;"><i class="icon-trash icon-white"></i> 删除</a>
            <a class="btn blue thickbox" title='添加新项目' href="@Url.Action("Create")?TB_iframe=true&height=200&width=400"><i class="icon-plus icon-white"></i> 新增</a>
        </div>
    </div>
    <div class="span8">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search" }))
        { 
        <div class="dataTables_filter">
            <label>
                <button type="submit" class="btn">搜索 <i class="icon-search"></i></button>
             </label>
            <label>
                <span>名称：</span>
                @Html.TextBox("Name", null, new { @class = "m-wrap small" })
            </label>
        </div>
        }
    </div>
</div>

@using (Html.BeginForm("Delete", "Project", FormMethod.Post, new { id = "mainForm" }))
{
<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th style="width: 8px;">
                <input type="checkbox" id="checkall" class="group-checkable" />
            </th>
            <th>
                名称
            </th>
            <th>
                创建时间
            </th>
            <th>
                操作
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
        <tr>
            <td>
                <input type="checkbox" class="checkboxes" name='ids' value='@m.ID' />
            </td>
            <td>
                @m.Name
            </td>
            <td>
                @m.CreateTime.ToCnDataString()
            </td>
            <td>
                <a class="btn mini purple thickbox" title='编辑项目内容' href="@Url.Action("Edit", new { id = m.ID })?TB_iframe=true&height=200&width=400">
                    <i class="icon-edit"></i>
                    编辑
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>
