iFramework.Web.Admin/Areas/Crm/Controllers/ParkingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using iFramework.Account.Contract;
using iFramework.Crm.Contract;
using iFramework.Framework.Contract;
using iFramework.Framework.Utility;
using iFramework.Web.Admin.Common;

namespace iFramework.Web.Admin.Areas.Crm.Controllers
{
    [Permission(EnumBusinessPermission.CrmManage_Parking)]
    public class ParkingController : AdminControllerBase
    {
        //
        // GET: /Crm/Parking/

        public ActionResult Index(ParkingRequest request)
        {
            this.TryUpdateModel<Parking>(request.Parking);

            this.ModelState.Clear();
            this.RenderMyViewData(request.Parking, true);
            var result = this.CrmService.GetParkingList(request);
            return View(result);
        }


        public ActionResult Create()
        {
            var model = new Parking() { };
            this.RenderMyViewData(model);
            return View("Edit", model);
        }

        //
        // POST: /Crm/Project/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var model = new Parking();
            this.TryUpdateModel<Parking>(model);

            try
            {
                this.CrmService.SaveParking(model);
            }
            catch (BusinessException e)
            {
                this.ModelState.AddModelError(e.Name, e.Message);
                this.RenderMyViewData(model);
                return View("Edit", model);
            }

            return this.RefreshParent();
        }

        //
        // GET: /Crm/Project/Edit/5

        public ActionResult Edit(int id)
        {
            var model = this.CrmService.GetParking(id);
            this.RenderMyViewData(model);
            return View(model);
        }

        //
        // POST: /Crm/Project/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var model = this.CrmService.GetParking(id);
            this.TryUpdateModel<Parking>(model);

            try
            {
                this.CrmService.SaveParking(model);
            }
            catch (BusinessException e)
            {
                this.ModelState.AddModelError(e.Name, e.Message);
                this.RenderMyViewData(model);
                return View("Edit", model);
            }

            return this.RefreshParent();
        }

        public ActionResult ManageBerth(int id)
        {
            var model = this.CrmService.GetParking(id);
            this.RenderMyViewData(model);
            return PartialView("ManageBerth");
        }

        //
        // POST: /Crm/Project/Edit/5

        [HttpPost]
        public ActionResult ManageBerth(int id, FormCollection collection)
        {
            var model = this.CrmService.GetParking(id);
            this.TryUpdateModel<Parking>(model);

            try
            {
                this.CrmService.SaveParking(model);
            }
            catch (BusinessException e)
            {
                this.ModelState.AddModelError(e.Name, e.Message);
                this.RenderMyViewData(model);
                return View("Edit", model);
            }

            return this.RefreshParent();
        }

        // POST: /Crm/VisitRecord/Delete/5

        [HttpPost]
        public ActionResult Delete(List<int> ids)
        {
            this.CrmService.DeleteVisitRecord(ids);
            return RedirectToAction("Index");
        }

        private void RenderMyViewData(Parking model, bool isBasic = false)
        {
            ViewData.Add("ParkingType", new SelectList(EnumHelper.GetItemValueList<EnumParkingType>(), "Key", "Value", model.ParkingType));
            ViewData.Add("CostAreaType", new SelectList(EnumHelper.GetItemValueList<EnumCostAreaType>(), "Key", "Value", model.CostAreaType));
        }
    }
}

iFramework.Web.Admin/Areas/Crm/Views/Parking/Edit.cshtml
@using iFramework.Cms.Contract
@using iFramework.Framework.Contract
@using iFramework.Framework.Web.Controls
@using iFramework.Crm.Contract
@using iFramework.Web
@model Parking
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}

@section PageSpecificStyleSheetIncludes{
    <link rel="stylesheet" type="text/css" href="@Url.StaticFile("~/assets/jquery-tags-input/jquery.tagsinput.css")" />
    <style>
        .hottag {
            margin: 2px;
            padding: 5px;
            cursor: pointer;
        }
    </style>
}
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="@Url.StaticFile("~/content/scripts/flashupload.js")"></script>
    <script type="text/javascript" src="@Url.StaticFile("~/content/xheditor/xheditor-1.1.6-zh-cn.min.js")"></script>
    <script type="text/javascript" src="@Url.StaticFile("~/assets/jquery-tags-input/jquery.tagsinput.js")"></script>
    <script type="text/javascript">
        $('#uploader').FileUpload({
            'subfolder': 'cms',
            'callback': function (msg) {
                //msg.url为图片地址
                $("#CoverPicture").val(msg.url);
                $("#preview").popover({ trigger: 'hover', html: true, placement: 'right ', content: "<img src='" + getThumbAbsoluteUrl(msg.url) + "'/>" });
            }
        });

        if ($("#CoverPicture").val()) {
            $("#preview").popover({ trigger: 'hover', html: true, placement: 'right ', content: "<img src='" + getThumbAbsoluteUrl($("#CoverPicture").val()) + "'/>" });
        }

        $("#Content").xheditor();

        $('#TagString').tagsInput({ 'width': 'auto', 'height': '90px', 'defaultText': '新增标签' });

        $(".hottag").click(function () {

            if (!$('#TagString').tagExist($(this).text())) {
                $('#TagString').addTag($(this).text());
            }
        });
    </script>
}
@section MainContent{
    <div class="tabbable tabbable-custom">
        <ul class="nav nav-tabs tabs-left">
            <li class="active"><a href="#tab1" data-toggle="tab">基本信息</a></li>
            <li><a href="#tab2" data-toggle="tab">泊位设置</a></li>
            <li><a href="#tab3" data-toggle="tab">标签设置</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">

                <div class="portlet-body form-horizontal form-bordered form-row-stripped">
                    <div class="row-fluid">

                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>泊站编号：</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.ParkingNo, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.ParkingNo)</span>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>泊站名称：</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.ParkingName, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.ParkingName)</span>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>泊位数量：</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.BerthNum, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.BerthNum)</span>
                            </div>
                        </div>
                     
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>泊站类型：</label>
                            <div class="controls">
                                @Html.DropDownList("ParkingType")
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.ParkingType)</span>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>收费类型：</label>
                            <div class="controls">
                                @Html.DropDownList("CostAreaType")
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.CostAreaType)</span>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>经纬度：</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.ParkingLat, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.ParkingLat)</span>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>地点名称：</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.PlaceName, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.PlaceName)</span>
                            </div>
                        </div>
                        
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>所属行政区：</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.RegionId, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.RegionId)</span>
                            </div>
                        </div>

                        <div class="control-group">
                            <label class="control-label">是否激活：</label>
                            <div class="controls">
                                @Html.CheckBoxFor(m => m.IsActive)
                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <div class="tab-pane" id="tab2">
            </div>
            <div class="tab-pane" id="tab3">
                <div class="portlet-body form-horizontal">

                    <div class="control-group">
                        <label class="control-label">标签</label>
                        <div class="controls">
                            
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

}

iFramework.Web.Admin/Areas/Crm/Views/Parking/Index.cshtml
@using iFramework.Framework.Contract
@using iFramework.Crm.Contract
@using iFramework.Framework.Utility
@using iFramework.Framework.Web.Controls
@using iFramework.Web.Admin.Common

@model PagedList<Parking>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section PageSpecificStyleSheetIncludes{
    <style type="text/css">
        select {
            margin: 1px;
            width: 150px;
        }

        .p5 {
            padding: 0px;
            padding-top: 5px;
            line-height: 200%;
            background: #fbfbfb;
        }

        .p5 label {
            width: 80px;
            text-align: right;
        }

        .p5 select {
            width: 133px;
        }

        #hourslider {
            display: inline-block;
            width: 120px;
            margin-top: 10px;
            margin-left: 30px;
        }
    </style>
}
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript">
        $(document).ready(function () {
            var dates = $("#startDate, #endDate").datepicker({
                dateFormat: "yy-mm-dd",
                defaultDate: "+1w",
                changeMonth: true,
                numberOfMonths: 2,
                onSelect: function (selectedDate) {
                    var option = this.id == "startDate" ? "minDate" : "maxDate",
					instance = $(this).data("datepicker"),
					date = $.datepicker.parseDate(
						instance.settings.dateFormat ||
						$.datepicker._defaults.dateFormat,
						selectedDate, instance.settings);
                    dates.not(this).datepicker("option", option, date);
                }
            });

            $("#username").autocomplete({
                source: '@Url.Action("GetUserNames", "Ajax")',
                minLength: 1,
                select: function (event, ui) {
                }
            });

            $("#Customer_Name").autocomplete({
                source: '@Url.Action("GetCustomerNames", "Ajax")',
                minLength: 1,
                select: function (event, ui) {
                }
            });

            $("#hourslider").slider({
                range: true,
                min: 0,
                max: 24,
                step: 1,
                values: [$("#startHour").val(), $("#endHour").val()],
                slide: function (e, ui) {
                    var timeText = getTime(ui.values[0]) + " - " + getTime(ui.values[1]);
                    $('#timetext').html(timeText);

                    $("#startHour").val(ui.values[0]);
                    $("#endHour").val(ui.values[1]);
                }
            });

            var timeText = getTime(parseInt($("#startHour").val())) + "-" + getTime(parseInt($("#endHour").val()));
            $('#timetext').html(timeText);
        });

        function getTime(value) {
            var hours = value;
            if (hours < 10) hours = '0' + hours;
            return hours + ':00';
        }

    </script>
}

    <div>
        <div>
            <a class="btn blue thickbox" title='添加新来电记录' href="@Url.Action("Create")?TB_iframe=true&height=600&width=600"><i class="icon-plus icon-white"></i> 新增</a>

            <a class="btn red" id="delete" href="javascript:;"><i class="icon-trash icon-white"></i> 删除</a>

            <a class="btn purple" data-toggle="collapse" data-parent="#accordion" href="#collapse"><i class="icon-double-angle-down icon-white"></i> 展开</a>
        </div>
        <br />
        <div id="collapse" class="collapse">
            <div class="row-fluid">
                <div class="span11">
                    
                </div>
            </div>
        </div>
    </div>


@using (Html.BeginForm("Delete", "Parking", FormMethod.Post, new { id = "mainForm" }))
{
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th style="width: 8px;">
                    <input type="checkbox" id="checkall" class="group-checkable" />
                </th>
                <th width="50">
                    编号
                </th>
                <th>
                    泊站名
                </th>
                <th>
                    泊位数量
                </th>
                <th>
                    泊站类型
                </th>
                <th>
                    收费类型
                </th>
                <th>
                    经纬度
                </th>
                <th>
                    地点名称
                </th>
                <th>
                    所属行政区
                </th>
                <th>
                    是否启用
                </th>
                <th>
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="checkboxes" name='ids' value='@p.ID' />
                    </td>
                    <td class="blue">
                        <span>@(p.ParkingNo)</span>
                    </td>
                    <td>
                        <span>@(p.ParkingName)</span>
                    </td>
                    <td>
                        <span>@(p.BerthNum)</span>
                    </td>
                    <td>
                        <span>@EnumHelper.GetEnumTitle((EnumParkingType)p.ParkingType)</span>
                    </td>
                    <td>
                        <span>@EnumHelper.GetEnumTitle((EnumCostAreaType)p.CostAreaType)</span>
                    </td>
                    <td>
                        <span>@(StringUtil.CutString(p.ParkingLat.ToString(),8))</span>
                        <span>,@(StringUtil.CutString(p.ParkingLng.ToString(), 8))</span>
                    </td>
                    <td>
                        <span>@(p.PlaceName ?? string.Empty)</span>
                    </td>
                    <td>
                        <span>@(p.RegionId)</span>
                    </td>
                    <td>
                        <span class="label label-@(p.IsActive  ? "success" : "inverse")">@p.IsActive</span>
                    </td>
                    <td>
                        <a class="btn mini purple thickbox" title='管理泊位' href="@Url.Action("ManageBerth", new { id = p.ID })?TB_iframe=true&height=600&width=600">
                            <i class="icon-edit"></i>
                            泊位管理
                        </a>
                    </td>
                    <td>
                        <a class="btn mini purple thickbox" title='编辑泊站记录内容' href="@Url.Action("Edit", new { id = p.ID })?TB_iframe=true&height=600&width=600">
                            <i class="icon-edit"></i>
                            编辑
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}


<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>